name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE with PyInstaller (bundle all)
        shell: bash
        run: |
          pyinstaller app.py \
            --onefile --noconsole \
            --icon assets/app.ico \
            --name AjedrezCPL \
            --add-data "assets;assets"
          ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AjedrezCPL-dist
          path: dist/**
