name: Build Windows EXE (onedir)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Verify assets
        shell: pwsh
        run: |
          if (-not (Test-Path .\assets\app.ico)) { throw 'Falta assets/app.ico' }
          if (-not (Test-Path .\assets\stockfish\stockfish.exe)) { Write-Warning 'No se encontró assets/stockfish/stockfish.exe' }
          Get-ChildItem -Recurse assets | Select-Object FullName, Length

      - name: Build (PyInstaller onedir)
        shell: bash
        run: |
          # Elimina .spec previo para evitar que fuerce configuración antigua
          rm -f *.spec
          pyinstaller app.py             --onedir --windowed             --name AjedrezCPL             --icon assets/app.ico             --add-data "assets;assets"             --collect-all PySide6             --collect-all shiboken6
          ls -la dist
          ls -la dist/AjedrezCPL || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AjedrezCPL-onedir
          path: dist/AjedrezCPL/**

